# Generated by Django 4.1.1 on 2022-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forget_pwd_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
