# Generated by Django 4.1.1 on 2022-11-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_forget_pwd_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
