# Generated by Django 4.1.1 on 2023-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
