# Generated by Django 4.1.1 on 2023-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderId',
            field=models.IntegerField(),
        ),
    ]
