# Generated by Django 4.1.1 on 2023-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='payed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
