# Generated by Django 4.1.1 on 2022-11-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_name_az_category_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_az',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
