# Generated by Django 4.1.1 on 2022-11-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_slug_az_category_slug_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
    ]
