# Generated by Django 4.1.1 on 2022-12-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(null=True, upload_to='static/assets/media/product_img'),
        ),
    ]
