# Generated by Django 4.1.1 on 2023-01-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_main_img_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
