# Generated by Django 4.1.1 on 2023-01-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_options_alter_propertyvalue_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='actual_price',
        ),
    ]
